language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
after_success:
  - npm run pre-publish
before_deploy:
  - cd dist
deploy:
  - npm publish
after_deploy:
  - npm run post-publish
branches:
  only:
    - /^angular\d+$/
