language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
after_success:
  - npm run semantic-release
deploy:
  skip_cleanup: true
branches:
  only:
    - /^angular\d+$/
